version: '3'

services:
  web:
    build: ./probeg
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./probeg:/app
    ports:
      - '8000:8000'
    depends_on:
      - db
  db:
    image: arm64v8/mysql:oracle
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql