version: '3'

services:
  web:
    build: ./probeg
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./probeg:/app
    ports:
      - '80:8000'
    depends_on:
      - db
  db:
    image: mysql:8.0.2
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "probegorg"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql


