version: '3'

services:
  web:
    build: ./probeg
    restart: always
    volumes:
      - ./probeg:/app
    command: gunicorn probeg.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: mysql:8.0.2
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_DATABASE: "probegorg"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
  nginx:
    build: ./nginx
    volumes:
       - ./probeg:/app
       - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
       - /etc/ssl/run-star.crt:/etc/ssl/run-star.crt
       - /etc/ssl/run-star.key:/etc/ssl/run-star.key
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - web


volumes:
  static_volume:

