# Generated by Django 4.1.8 on 2023-04-13 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogindexpage_blogpage_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BlogIndexPage',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
